### PR TITLE
V622 pair offset

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- release = CMSSW_11_2_ROOT622_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@pcanal , I am merging this in CMSSW v6.22 branch so that we can run full tests in IB

**Comment by pcanal** [comment]
@smuzaffar Some result seems to have come up.  Does it mean we are all good or is there more to come?

**Comment by smuzaffar** [comment]
not really @pcanal , for PR tets we run in non-threaded mode so tests passigng here does not mean that there are no issue. This is now in IB whee we will relvals in threaded mode and there we will see if any issue pops up. Sometimes it takes few IBs to get threaded issues

**Pull request merged**
