### PR TITLE
[v6.24] Cling: prevent double release of Transactions

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6777

**Comment by smuzaffar** [comment]
@slava77  , can you please check these reco comparison differences? These are for root 6.24 based cmssw

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6777

**Comment by smuzaffar** [comment]
test parameters:
- disable_poison = true

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6777

**Comment by slava77** [comment]
> @slava77 , can you please check these reco comparison differences? These are for root 6.24 based cmssw

the differences look like the baseline was different in more than jut this PR; most likely in cms-sw/cmsdist#6769 

the tests were done on top of CMSSW_11_3_ROOT624_X_2021-03-29-2300, which is made before cms-sw/cmsdist#6769 was merged.
It would be nice to add a summary of extra commits in the test summary.

**Comment by smuzaffar** [comment]
Thanks @slava77 for your analysis. As I have restarted the tests, so hopefully comparisons should be better now.
About the extra commits, yes looks like bot was only doing it when cmssw PRs are involved. I have updated it  ( https://github.com/cms-sw/cms-bot/pull/1529/files ) and now extra commits should be added for all PR tests

**Comment by smuzaffar** [comment]
comparison results look better now

**Comment by smuzaffar** [comment]
please test with cms-sw/cms-bot#1530,cms-sw/cmsdist#6777

**Pull request closed without merging**
