### PR TITLE
Revert three more Clang patches from hahnjo:revert-clang-patches

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Testing https://github.com/root-project/root/pull/13181.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test for CMSSW_13_2_ROOT6_X

**Comment by smuzaffar** [comment]
thanks @aandvalenzuela for testing it. By the you do not need to copy the branch, you can use the https://github.com/hahnjo/root/tree/revert-clang-patches branch directly to open PR.  This way when author pushes any thing to his/her branch then we also get those change here

**Comment by aandvalenzuela** [comment]
Thanks @smuzaffar! I tried, but although https://github.com/hahnjo/root fork seems to be public, I could not select it as a head repo:

Captura de Pantalla 2023-07-06 a la(s) 2 39 24 p m

Not even writing the entire fork name:

Captura de Pantalla 2023-07-06 a la(s) 2 44 33 p m

Just out of curiosity @hahnjo, do you have any special protection for that?

**Comment by hahnjo** [comment]
Not that I'm aware of; can you see the "Compare" buttons on https://github.com/hahnjo/root/branches ?

**Comment by aandvalenzuela** [comment]
> Not that I'm aware of; can you see the "Compare" buttons on https://github.com/hahnjo/root/branches ?

Yes! Now I can compare https://github.com/cms-sw/root/compare/cms/master/7f288f1ca8...hahnjo:root:revert-clang-patches. Mmmm... I wonder why it did not work the other way

**Comment by aandvalenzuela** [comment]
For CMSSW, tests `testDataFormatsScoutingRun2/3` and `testUCTUnpacker` are also failing in the [integration builds](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc11/www/wed/13.2.ROOT6-wed-23/CMSSW_13_2_ROOT6_X_2023-07-05-2300?utests).

**Comment by aandvalenzuela** [comment]
https://github.com/root-project/root/pull/13181 was completed!

**Pull request closed without merging**
