### PR TITLE
Applying latest ROOT commits to branch V6-26-00-patches

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by smuzaffar** [comment]
why this PR @aandvalenzuela ?

**Comment by aandvalenzuela** [comment]
I created the branch `cms/v6-26-00-patches/2f336483c6` in `cms-sw/root` from the lastest v6.26 branch in our repo (https://github.com/cms-sw/root/tree/cms/v6-26-00-patches/a25c523160) and applied the commits from the v6.26 branch in `root-project/root` (https://github.com/root-project/root/tree/v6-26-00-patches)

**Comment by smuzaffar** [comment]
did our normal proceedure to update root not work for this? I mean running https://github.com/cms-sw/cms-bot/blob/master/cmsdist-tool-update.sh for IB/CMSSW_13_3_X/master ?

**Comment by smuzaffar** [comment]
I am deleting [cms/v6-26-00-patches/2f336483c6](https://github.com/cms-sw/root/tree/cms/v6-26-00-patches/2f336483c6)  branch now and please use the [cmsdist-tool-update.sh](https://github.com/cms-sw/cms-bot/blob/master/cmsdist-tool-update.sh) for updating

**Comment by aandvalenzuela** [comment]
It was creating a `cms/master/XXXXXXXXXX` branch instead of `cms/v6-26-00-patches/XXXXXXXXXX`

**Comment by aandvalenzuela** [comment]
Okay, let me retry! Thanks

**Comment by smuzaffar** [comment]
> It was creating a `cms/master/XXXXXXXXXX` branch instead of `cms/v6-26-00-patches/XXXXXXXXXX`

you might have used wrong cmsdist branch. if you have used `IB/CMSSW_13_3_X/master` and script was creating `cms/master/XXXXXXXXXX` then we should fix the script

**Comment by aandvalenzuela** [comment]
You are right, sorry for the noise!

**Comment by aandvalenzuela** [comment]
See https://github.com/cms-sw/cmsdist/pull/8630

**Pull request merged**
