### PR TITLE
Disable rdict files

### PR DESCRIPTION
**Pull request by vgvassilev**
cc @smuzaffar, @davidlange6, @Axel-Naumann

"@smuzaffar we'll need your help to know what to do, based on realistic numbers. We would very much appreciate if you could compare:

   * a ROOT build without modules, and with this PR (i.e. without rdict.pcm files),
   * compared to a ROOT build without modules (still!), without this PR (i.e. with rdict.pcm files)

I.e. always non-modularized ROOT, with vs without this PR.

We're interested in the change in RSS and real time, for a reco on say a single event with a small event size, e.g. minbias. Do you think you could help us with this?"

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_ROOT6_X

**Comment by smuzaffar** [comment]
@vgvassilev , do you need all these commits to be part of this PR?

**Comment by vgvassilev** [comment]
No, I don’t think so. However I doubt they hurt.

**Comment by smuzaffar** [comment]
@vgvassilev , build failed as now root tells us the checksum of all our dictionaries are different
```
>> Checking EDM Class Transients in libDataFormatsDetId.so
error: class 'SiPixelRawDataError' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 3708678642
@@@@ ----> OK  EDM Class Version 
>> Checking EDM Class Transients in libDataFormatsL1DTTrackFinder.so
Suggestion: You can run 'scram build updateclassversion' to generate src/DataFormats/SiPixelRawData/src/classes_def.xml.generated with updated ClassVersion
gmake: *** [tmp/slc7_amd64_gcc700/edm_checks/libDataFormatsSiPixelRawData.so] Error 1
>> Checking EDM Class Version for src/DataFormats/L1TMuon/src/classes_def.xml in libDataFormatsL1TMuon.so
@@@@ ----> OK  EDM Class Version 
>> Checking EDM Class Transients in libDataFormatsScalers.so
@@@@ ----> OK  EDM Class Version 
>> Checking EDM Class Transients in libSimTrackerTrackHistory.so
@@@@ ----> OK  EDM Class Version 
>> Checking EDM Class Transients in libDataFormatsHcalDetId.so
@@@@ ----> OK  EDM Class Version 
>> Checking EDM Class Transients in libDataFormatsL1GlobalCaloTrigger.so
error: class 'SiStripLaserRecHit2D' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 2562318399
Suggestion: You can run 'scram build updateclassversion' to generate src/DataFormats/Alignment/src/classes_def.xml.generated with updated ClassVersion
@@@@ ----> OK  EDM Class Version 

```

**Comment by pcanal** [comment]
humm odd ... looking at https://github.com/cms-sw/cmssw/blob/master/DataFormats/SiPixelRawData/interface/SiPixelRawDataError.h

The 'only' way I can think this could happen is if 'cling' (ie. root run-time) sees a different definition of  cms_uint32_t  or cms_uint64_t  than `rootcling/genreflex` (i.e compile time).

but according to https://github.com/cms-sw/cmssw/blob/ce6799f9c415132bc64dd84b26fc7d2639e1cea8/FWCore/Utilities/interface/typedefs.h

that is not 'possible' either ....

So maybe there is 'stale' rdict_pcm files laying around (and accessible via some of the environment variable.

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_ROOT6_X

humm that might be as the tests were run against a patch cmssw IB. let me start the tests against a full release.

**Comment by smuzaffar** [comment]
its failed again with same error. I will build it locally (on cmsdev machine) and will ask you to check why we are getting this error.

**Comment by smuzaffar** [comment]
@pcanal , @vgvassilev building cmssw fail with root change. I tried locally and I get the following error
```
src/FWCore/Utilities/scripts/edmCheckClassVersion -l tmp/slc7_amd64_gcc820/src/DataFormats/Provenance/src/DataFormatsProvenance/libDataFormatsProvenance.so -x src/DataFormats/Provenance/src/classes_def.xml
Error in <TInterpreter::TCling::AutoLoad>: failure loading library libDataFormatsProvenance.so for edm::BranchType
error: class 'edm::FileIndex' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 3273609006
error: class 'edm::ProcessConfiguration' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 4289262527
error: class 'edm::Parentage' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 4208679056
error: class 'edm::BranchDescription' has a different checksum for ClassVersion 13. Increment ClassVersion to 14 and assign it to checksum 2459098876
error: class 'edm::ProcessHistory' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 139999391
error: class 'edm::ModuleDescription' has a different checksum for ClassVersion 10. Increment ClassVersion to 11 and assign it to checksum 2309062167
error: class 'edm::IndexIntoFile' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 1190117343
error: class 'edm::ProductRegistry' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 1774599429
```

I do not see any _rdict.pcm loaded ( find the strace output here  http://cern.ch/muzaffar/root_rdict.log)

**Comment by smuzaffar** [comment]
any idea @vgvassilev , @pcanal ? I tried latest root updates + this change here ( #135 ) but still same error.

**Comment by vgvassilev** [comment]
I have no idea. The rdict files cache the checksums of the root files streamer infos. It is unlikely but they may have shadowed a real data model changes which required a classdef version bump. If you can set up a debug build @pcanal and I probably can debug it.

**Comment by smuzaffar** [comment]
you can run following commands on cmsdev21 to re-produce and debug it
```
scram p /build/muz/root_rdict/w/tmp/BUILDROOT/38bf3401ae81d6d963bff0ba75f2db99/opt/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_ROOT6_X_2019-09-08-2300
cd CMSSW_11_0_ROOT6_X_2019-09-08-2300/
cmsenv
git cms-addpkg DataFormats/Provenance
scram b -v -j 10 
```
this should fail with the error and scram will delete the generated shared lib. In order to dubug, copy/paste and run the link line used by scram to generate libDataFormatsProvenance.so and run edmCheckClassVersion e.g.

```
/compiler/c++ -O2 -pthread -pipe -Werror=main -Werror=pointer-arith ......
$CMSSW_RELEASE_BASE/src/FWCore/Utilities/scripts/edmCheckClassVersion -l tmp/slc7_amd64_gcc820/src/DataFormats/Provenance/src/DataFormatsProvenance/libDataFormatsProvenance.so -x src/DataFormats/Provenance/src/classes_def.xml
```

**Comment by pcanal** [comment]
Can you also setup me with a 'regular' debug version for comparison?  Thanks.

**Comment by smuzaffar** [comment]
root in normal ROOT6 IBs is build in debug mode, so you can just create dev area using any ROOT6 IB e.g.
```
scram p CMSSW_11_0_ROOT6_X_2019-09-11-2300
cd CMSSW_11_0_ROOT6_X_2019-09-11-2300
cmsenv
git cms-addpkg DataFormats/Provenance
scram b -v -j 10 
```

**Comment by pcanal** [comment]
ah right ... this won't work without more work (on the hack-root side)

Ever since commit 2910b21e87ad856cda75e74db7a7f96331f8a386 (there may be or may not not be additional related commits), the **only** source of information for the tag from the selection.xml file is the rootpcm ... Prior to this, we used to generate code in the C++ dictionary that contains the information  from the selection.xml (in particular in regard to data members), this is no longer the case as this information is 'now' also in the rootpcm (and thus the c++ version was a duplicate and waster of time and space :) ).

The 'reason' the checksum is different here is that all the 'transient' members are now thought to be persistent.

**Comment by vgvassilev** [comment]
@pcanal what would be the way forward here?

**Comment by smuzaffar** [comment]
do we still need this?

**Comment by vgvassilev** [comment]
No, I will close it.

**Pull request closed without merging**
