### PR TITLE
Thread-safe TClass enums

### PR DESCRIPTION
**Pull request by Dr15Jones**
This fixes problems using enums with cutParser.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@ktf

**Comment by Dr15Jones** [comment]
This should fix the last found issue with ROOT 6 and threading.

**Comment by Dr15Jones** [comment]
Thanks

**Comment by ktf** [comment]
I think this broke mctester:

https://cmssdt.cern.ch/jenkins/job/build-any-ib/6501/console

**Comment by ktf** [comment]
Full error is:

```
/build/cmsbuild/jenkins-workarea/workspace/build-cache/cms.week0/w/slc6_amd64_gcc491/lcg/root/6.02.00-lnjiaj3/bin/rootcling -f HEPEventDict.cxx -D_USE_ROOT_ HEPParticle.H HEPEvent.H LUJETSEvent.H LUJETSParticle.H PYJETSEvent.H PYJETSParticle.H HerwigParticle.H HerwigEvent.H HEPEVTEvent.H HEPEVTParticle.H THEPEvent.H   THEPParticle.H MC3Vector.H MC4Vector.H LinkDef.h

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x000000355c0ac61e in waitpid () from /lib64/libc.so.6
#1  0x000000355c03e609 in do_system () from /lib64/libc.so.6
#2  0x0000000000ad8337 in TUnixSystem::StackTrace() ()
#3  0x0000000000ada2cc in TUnixSystem::DispatchSignals(ESignals) ()
#4  <signal handler called>
#5  0x0000000000a87710 in THashList::FindObject(char const*) const ()#6  0x0000000000ab19c4 in TEnum::GetEnum(char const*, TEnum::ESearchAction) ()#7  0x0000000000aae3ea in TDataMember::Init(bool) ()#8  0x0000000000aaedaf in TDataMember::TDataMember(DataMemberInfo_t*, TClass*) ()#9  0x0000000000ab8265 in TListOfDataMembers::Get(DataMemberInfo_t*) ()#10 0x0000000000ab84a3 in TListOfDataMembers::Load() ()
#11 0x0000000000a9601b in TClass::GetListOfDataMembers(bool) ()
#12 0x0000000000aa26da in TClass::GetDataMember(char const*) const ()#13 0x0000000000aa59fe in TBuildRealData::Inspect(TClass*, char const*, char const*, void const*, bool) ()
#14 0x0000000000d31954 in TCling::InspectMembers(TMemberInspector&, void const*, TClass const*, bool) ()
#15 0x0000000000d31e16 in TCling::InspectMembers(TMemberInspector&, void const*, TClass const*, bool) ()
#16 0x0000000000a98210 in TClass::CallShowMembers(void const*, TMemberInspector&, bool) const ()#17 0x0000000000aa4187 in TClass::BuildRealData(void*, bool) ()
#18 0x0000000000ac1659 in TProtoClass::TProtoClass(TClass*) ()
#19 0x00000000008f54f4 in CloseStreamerInfoROOTFile ()
#20 0x00000000008b38be in FinalizeStreamerInfoWriting(cling::Interpreter&, bool) ()
#21 0x00000000008b5775 in GenerateFullDict(std::basic_ostream<char, std::char_traits<char> >&, cling::Interpreter&, RScanner&, std::list<ROOT::TMetaUtils::RConstructorType, std::allocator<ROOT::TMetaUtils::RConstructorType> > const&, bool, bool, bool) ()
#22 0x00000000008c2dce in RootCling(int, char**, bool, bool) ()#23 0x00000000008917d7 in main ()===========================================================
```

**Comment by Dr15Jones** [comment]
I'll look at this first thing this morning

**Comment by Dr15Jones** [comment]
Is there a release available with the problem?

**Comment by davidlt** [comment]
@Dr15Jones no, this is blocking external from building. IIRC it generates some ROOT dictionaries when building.

**Pull request merged**
