### PR TITLE
Update 6.02.12 to the tip of the branch.

### PR DESCRIPTION
**Pull request by degano**

### CODE REVIEW

**Comment by davidlt** [comment]
This is not the way it is supposed to be done. A branch should be created `cms/hash_at_fork` and custom patches applies on top.

**Comment by degano** [comment]
We should discuss this in private as there is more than that.

**Comment by smuzaffar** [comment]
yes, I am also not sure about this... lets discuss offline

**Comment by davidlt** [comment]
Again the policy was to use `cms/hash_at_fork`where it fully matches original source with custom stuff on top. Then we advertised people to use `git diff hash_at_fork..HEAD` or `git log hash_at_fork..HEAD` to see what CMS added extra on top. Makes it easy to track the differences.

E.g., ROOT 6.04.

```
$ git log --oneline 75d7131..HEAD
fb0504b Assert to error: cannot autoload that, its declaring header cannot be found at runtime! (cherry picked from commit 715544a9eeea55cd3f2e7ee10c307501505b78eb)
5998a15 Use a lock to protect access to collection from TROOT::GetListOfCleanups()
```

As long as keep this working, we can write tooling on top of it future.

**Pull request merged**
