### PR TITLE
Update ROOT's llvm to llvm13

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#8192

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8192

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- release = CMSSW_13_0_ROOT6_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
Is this the error?
```
-- Configuring incomplete, errors occurred!
See also "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc11/lcg/root/6.24.07-7590b535ccf260d774290b0411ae071a/build/CMakeFiles/CMakeOutput.log".
See also "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc11/lcg/root/6.24.07-7590b535ccf260d774290b0411ae071a/build/CMakeFiles/CMakeError.log".
error: Bad exit status from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/tmp/rpm-tmp.pYXJdV (%build)


RPM build errors:
line 37: It's not recommended to have unversioned Obsoletes: Obsoletes: lcg+root+6.24.07-7590b535ccf260d774290b0411ae071a
Macro expanded in comment on line 333: %{pkginstroot}/lib

Macro expanded in comment on line 334: %{pkginstroot}

Bad exit status from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/tmp/rpm-tmp.pYXJdV (%build)
```

**Comment by smuzaffar** [comment]
@gartung , that was a mistake on our side, tests were started to use root master based on cmsdist default branch ( which it should have used cmsdist rootmaster branch). latest PR tests result [here](https://github.com/cms-sw/root/pull/177#issuecomment-1334773956) are good one

**Comment by smuzaffar** [comment]
please test
lets re-run based on latest IB

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#8223

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8223

using newer IB

**Comment by smuzaffar** [comment]
abort

**Pull request closed without merging**
