### PR TITLE
[Testing] Update ROOT and Cling to LLVM18

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Testing ROOT llvm18 update as requested in https://github.com/root-project/root/pull/15696#issuecomment-2310343351

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_1_ROOT6_X
* We moved today release cycle to 14_2_X, so the first IB for it will be available tonight

**Comment by dpiparo** [comment]
😱

**Comment by aandvalenzuela** [comment]
FYI, https://github.com/cms-sw/cms-bot/pull/2323 disables the check on the number of files in non-cmssw repositories, so that we can move forward with the testing

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_2_ROOT6_X

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_2_ROOT6_X

**Comment by iarspider** [comment]
please test for CMSSW_14_2_ROOT6_X/el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_ROOT6_X/el8_aarch64_gcc12

**Comment by hahnjo** [comment]
@smuzaffar @aandvalenzuela @iarspider I think I found the problem on AArch64 and pushed a fix. Can you retrigger testing, please?

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_2_ROOT6_X/el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_ROOT6_X

**Comment by hahnjo** [comment]
Okay, we definitely got further on AArch64... (without breaking x86_64)

> I found 3 errors in the following unit tests:
> 
> ---> test testPhysicsToolsSelectorUtilsPythonTestsDriver had ERRORS
> ---> test TestRunnerDataFormatsFWLite had ERRORS
> ---> test TestRunnerFWCoreTFWLiteSelector had ERRORS

Can somebody with access check what is the problem here? Are these "real" failures that we need to address from the ROOT side before merging the upgrade?

**Comment by hahnjo** [comment]
@smuzaffar @aandvalenzuela can you give this another try on AArch64, please? We're trying to switch the architecture to a new JIT linker infrastructure, which should solve the unit test crashes (at least according to our testing). The switch was planned anyway and we originally wanted to avoid doing it together with the upgrade, but it seems we are not able to solve the problems without deeply investigating into core LLVM code...

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_ROOT6_X/el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_ROOT6_X

**Comment by smuzaffar** [comment]
@hahnjo , aarch64 tests passed. The unit test `testSiStripPayloadInspector` failure is not related to this change ( it is already failing in cmssw IBs). 

Tests for x86_64 also look good

**Pull request closed without merging**
