### PR TITLE
612 backport of I/O rules and splitting improvements.

### PR DESCRIPTION
**Pull request by pcanal**

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#26205

**Comment by smuzaffar** [comment]
bot is not yet ready for this :-)
I can manually trigger tests once current tests of cms-sw/cmssw#26205 are done.

**Comment by fabiocos** [comment]
@smuzaffar ok, thanks

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar ok, so the bot does not understand this for this package I understand, we should test it now that the fix by @Dr15Jones has been merged

**Comment by smuzaffar** [comment]
ok, I am starting the tests now

**Comment by fabiocos** [comment]
@slava77 @perrotta FYI, there are no differences in the DQM comparison after the merge of cms-sw/cmssw@26205

**Comment by fabiocos** [comment]
+1

I would suggest to move forward with this fix

**Pull request merged**
