### PR TITLE
Backport jitlink ppc64

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- skip_test = static 
- full_cmssw = true
- pull_request = cms-sw/cmssw#43096, cms-sw/cmssw#43104, cms-externals/boost#6

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ROOT6_X

**Pull request closed without merging**
