### PR TITLE
Testing ROOT fix for TH2Poly class

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Testing https://github.com/root-project/root/pull/13267 for CMSSW.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
Waiting for tonight's `CMSSW_13_3_ROOT6_X` IB to start the testing

**Comment by smuzaffar** [comment]
too many commits here/ did you create this PR using the latest cms/master/<commit> ?

**Comment by aandvalenzuela** [comment]
Yes, but the last update was two weeks ago (https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_3_X/rootmaster/root.spec#L6), so I am getting all the commits since then (including the failed commit)

**Comment by smuzaffar** [comment]
ah ok, better to create a cms/master based on latest root commit and then use that as base branch for this PR

**Comment by aandvalenzuela** [comment]
Sure, thanks!

**Comment by aandvalenzuela** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by aandvalenzuela** [comment]
FYI, @smuzaffar
@linev, your commit fixes the failed tests. Unit tests `testDataFormatsScoutingRunX` are also failing in the IBs and they are known issues.

**Pull request closed without merging**
