### PR TITLE
Backport jitlink ppc64

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_14_0_ROOT6_X/el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test for CMSSW_14_0_ROOT6_X/el8_amd64_gcc12

**Comment by vgvassilev** [comment]
@smuzaffar, should we worry about this failure? Is it related to the new ppc backend or there is a problem somewhere else?

**Comment by smuzaffar** [comment]
No @vgvassilev , this unit tests is failing in our IBs anyway. So please ignore this failure.

**Pull request closed without merging**
