### PR TITLE
[tcling] Temporarily disable loading rdict files.

### PR DESCRIPTION
**Pull request by smuzaffar**
We want to use this pull request to measure the impact on the cmssw.
same as https://github.com/cms-sw/root/pull/134 but on top of latest root development.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_ROOT6_X

**Comment by vgvassilev** [comment]
@smuzaffar could you kick the bot to do something?

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_ROOT6_X

**Comment by davidlange6** [comment]
[0] Calling EventProcessor::runToCompletion (which does almost everything after beginJob and before endJob)
   Additional Info:
      [a] Fatal Root Error: @SUB=TExMap::Remove
key 140218829641800 not found at 1

**Comment by smuzaffar** [comment]
Do we need this any more?

**Comment by vgvassilev** [comment]
The issue seems resolved in a different way. We can close this pr.

**Pull request closed without merging**
