### PR TITLE
Add Philippe Canal's initial TClass thread-safety changes

### PR DESCRIPTION
**Pull request by Dr15Jones**
These are the first of the thread-safety changes we need. This code changes the memory layout for TClass and therefore breaks binary compatibility. Rather than applying these changes locally and then rebuilding all of CMSSW, it should be more productive to get these into the release and then any subsequent changes to ROOT which are binary compatible can be done without recompling CMSSW locally.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
These commits come from ROOT's v6-02-00-patches branch

**Comment by Dr15Jones** [comment]
@pcanal

**Comment by ktf** [comment]
@Dr15Jones we are basically abandoning the cms/v6-02-05 branch due to @wmtan request to move to the tip of  v6-02-00-patches (see the private email). Why this PR?

**Comment by Dr15Jones** [comment]
If you are moving us off the cms/v6-02-05 branch to another branch with these commits there then this pull request isn't necessary.

**Comment by Dr15Jones** [comment]
How are you handling our changes which aren't in v6-02-00-patches?

**Comment by ktf** [comment]
I moved us to:

cms-sw/root@a858615ec00da7d0c32579d0781b433d2964e9e7

which includes:

#59 

which should be the same, no?

**Comment by Dr15Jones** [comment]
I had cherry-picked the commits from ROOT's v6-02-00-patches branchs so they are the same.

**Comment by wmtan** [comment]
We should stay on the cms/v6-02-05 branch and just update it.  My apologies for the misunderstanding.  We should update the cms/v6-02-05 branch so it includes both of Lorenzo's fixes.
There are two choices, either update it with all the commits on the patches branch, or cherry pick *both( of Lorenzo's fixes, whichever is easier and/or safer.

**Comment by ktf** [comment]
ok. I'll clean this up at some point during the weekend. What I did a while ago should be pretty much equivalent, just not particularly clean.

**Comment by ktf** [comment]
For the record: I just switched back to the cms/v6-02-05 branch and 
picked up all the relevant additional commits by Lorenzo there. I also 
included some more MT fixes by Chris.

https://github.com/cms-sw/cmsdist/pull/1393

**Comment by Dr15Jones** [comment]
@ktf @davidlange6 These seems to have been missed during the 'move away from cms/v6-02-05 then move back to cms/v6-02-05'. 
I need these changes for further work in ROOT6.

**Comment by ktf** [comment]
Weird. I thought I picked them up... :-/

**Pull request merged**
