### PR TITLE
[PyROOT] Update cppyy to a recent version

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_ROOT6_X

**Comment by hahnjo** [comment]
https://github.com/root-project/root/pull/14507 has long been merged, I believe this can be closed

**Pull request closed without merging**
