### PR TITLE
Rebase for ROOT CMSSW cxxmodules branch

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by oshadura** [comment]
@smuzaffar Can you trigger builds please?

**Comment by mrodozov** [comment]
allow @oshadura test rights

**Comment by oshadura** [comment]
Please test

**Comment by smuzaffar** [comment]
abort
we can not test it against default IB. @oshadura we will test it once CXXMODULE IBs are in good state

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_CXXMODULE_X

**Comment by oshadura** [comment]
@smuzaffar I will try to build CXXMODULES IB locally, to see where is segfault coming from...

**Comment by smuzaffar** [comment]
Thanks @oshadura . Can you please also check why we get this error in IB
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc700/CMSSW_11_0_CXXMODULE_X_2019-06-11-2300/DataFormats/BTauReco
```
>> Checking EDM Class Transients in libDataFormatsBTauReco.so
/build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/dc2802585e194241b8afb9861018f198/opt/cmssw/slc7_amd64_gcc700/cms/cmssw/CMSSW_11_0_CXXMODULE_X_2019-06-11-2300/src/FWCore/Utilities/scripts/edmCheckClassTransients -l tmp/slc7_amd64_gcc700/src/DataFormats/BTauReco/src/DataFormatsBTauReco/libDataFormatsBTauReco.so -f lib/slc7_amd64_gcc700/DataFormatsBTauReco_xr.rootmap
Warning in <TInterpreter::ReadRootmapFile>: class  edm::RefVector<vector<int>,int,edm::refhelper::FindUsingAdvance<vector<int>,int> > found in libDataFormatsMath.so  is already in libDataFormatsCommon.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::ValueMap<bool> found in libDataFormatsMath.so  is already in libDataFormatsCommon.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::ValueMap<double> found in libDataFormatsMath.so  is already in libDataFormatsCommon.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::ValueMap<float> found in libDataFormatsMath.so  is already in libDataFormatsCommon.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::ValueMap<int> found in libDataFormatsMath.so  is already in libDataFormatsCommon.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::ValueMap<unsigned int> found in libDataFormatsMath.so  is already in libDataFormatsCommon.so 
TClassTable::Add:0: RuntimeWarning: class edm::RefVector<vector<int>,int,edm::refhelper::FindUsingAdvance<vector<int>,int> > already in TClassTable
TClassTable::Add:0: RuntimeWarning: class edm::ValueMap<double> already in TClassTable
TClassTable::Add:0: RuntimeWarning: class edm::ValueMap<float> already in TClassTable
TClassTable::Add:0: RuntimeWarning: class edm::ValueMap<unsigned int> already in TClassTable
TClassTable::Add:0: RuntimeWarning: class edm::ValueMap<bool> already in TClassTable
TClassTable::Add:0: RuntimeWarning: class edm::ValueMap<int> already in TClassTable
In file included from DataFormatsBTauReco_xr dictionary payload:73:
In file included from /build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/dc2802585e194241b8afb9861018f198/opt/cmssw/slc7_amd64_gcc700/cms/cmssw/CMSSW_11_0_CXXMODULE_X_2019-06-11-2300/src/DataFormats/BTauReco/interface/CombinedTauTagInfo.h:13:
In file included from /build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/LorentzVector.h:30:
  /build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/ThreeVector.h:41:7: error: redefinition of 'Hep3Vector'
 class Hep3Vector {
      ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/LorentzVector.h:30:10: note: '/build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/ThreeVector.h' included multiple times, additional include site here
#include "CLHEP/Vector/ThreeVector.h"
         ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/LorentzVector.h:30:10: note: '/build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/ThreeVector.h' included multiple times, additional include site here
#include "CLHEP/Vector/ThreeVector.h"
         ^
In file included from DataFormatsBTauReco_xr dictionary payload:73:
In file included from /build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/dc2802585e194241b8afb9861018f198/opt/cmssw/slc7_amd64_gcc700/cms/cmssw/CMSSW_11_0_CXXMODULE_X_2019-06-11-2300/src/DataFormats/BTauReco/interface/CombinedTauTagInfo.h:13:
In file included from /build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/LorentzVector.h:30:
In file included from /build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/ThreeVector.h:448:
  /build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/ThreeVector.icc:21:29: error: redefinition of 'operator[]'
 inline double & Hep3Vector::operator[] (int i)       { return operator()(i); }
                            ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc700/external/clhep/2.4.0.0-pafccj/include/CLHEP/Vector/ThreeVector.icc:21:29: note: previous definition is here
inline double & Hep3Vector::operator[] (int i)       { return operator()(i); }
                            ^
```

**Comment by smuzaffar** [comment]
also during PR tests we see these messages. These printed numbers are new, any idea about these?

```
>> Building edm plugin tmp/slc7_amd64_gcc700/src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/CalibCalorimetryEcalCorrelatedNoiseAnalysisModules/libCalibCalorimetryEcalCorrelatedNoiseAnalysisModules.so
Leaving library rule at CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules
@@@@ Running edmWriteConfigs for CalibCalorimetryEcalCorrelatedNoiseAnalysisModules
102
102
102
102
102
102
102
102
102
102
102
102
102
102
```

**Comment by oshadura** [comment]
@smuzaffar I didn't manage to reproduce build issues locally.. For me, it failed like this https://gist.github.com/oshadura/c93295765cd2ff22c3bf0c566ed73e84

@yamaguchi1024 recommended not to enable runtime modules for CLHEP. She explained me that it is very tricky since is ~ a wrapper of a system header, which doesn't have a modulemap.

About printed numbers, she told me it is for a debugging purposes..

**Pull request merged**
