### PR TITLE
[Testing] Delete the object held by gROOT after we reset the globals.

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Testing if https://github.com/root-project/root/pull/13463 solves https://github.com/root-project/root/issues/13429

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by aandvalenzuela** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by aandvalenzuela** [comment]
It seems tests are still failing due to https://github.com/root-project/root/issues/13429

**Comment by hahnjo** [comment]
> It seems tests are still failing due to [root-project#13429](https://github.com/root-project/root/issues/13429)

Ok, thanks for testing. Was worth a try, but then I have to get a debugger going...

**Comment by aandvalenzuela** [comment]
> > It seems tests are still failing due to [root-project#13429](https://github.com/root-project/root/issues/13429)
> 
> OK, thanks for testing. Was worth a try, but then I have to get a debugger going...

Right, I am trying to figure out why the reproducer does not work for you. Let's see if @smuzaffar can point out something on Monday.  I think we might be missing one config step since the file is supposed to be public. Otherwise, I can give you access to one of our machines and set up a development area for you there.

Sorry for the inconvenience! :)

**Comment by hahnjo** [comment]
I think this testing PR can be closed, the associated change was merged into ROOT `master` already last week. On the positive side, I made significant progress to understand https://github.com/root-project/root/issues/13429: A workaround in CMSSW is proposed in https://github.com/cms-sw/cmssw/pull/42628.

**Comment by smuzaffar** [comment]
@hahnjo , thanks a lot for looking in to the issue and providing a the cmssw fix https://github.com/cms-sw/cmssw/pull/42628

**Pull request closed without merging**
