### PR TITLE
Disable proofd file server for XRootD>=5

### PR DESCRIPTION
**Pull request by smuzaffar**
Patch is needed in order to backport the XrootD>=5 in to root 6.12/14. This basically disables the XProofD file server and client support for XRootD versions>=5. Thanks to Christopher H Green and Kyle Knoepfel  for providing this patch.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_10_6_X

**Comment by smuzaffar** [comment]
+externals

@perrotta @rappoccio any objections on merging this for CMSSW 10.6.X . This change allows us to backport xrootd 5 to 10.6.X

**Comment by rappoccio** [comment]
+1

Yes, please merge this. Once we get them all together, I assume the checks will pass?

**Comment by iarspider** [comment]
@rappoccio the failed unit test is not related to this PR, I think it's just a glitch. I will restart the test just in case

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
no need to test it any more. Anyway test should have been requested for CMSSW_10_6_X :-)

**Pull request merged**
