### PR TITLE
Llvm16

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- pull_request = https://github.com/cms-externals/boost/pull/5

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
@vgvassilev , one of the externals hepdata failed to build with root llvm16 [a]. I have retsarted the tests to [dropped hepdata](https://github.com/cms-sw/cmsdist/pull/8634) to see what else fails

[a]
```
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  input_line_1:1:2: fatal error: module file '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc11/lcg/root/6.29.01-21b454f32e2b6b83ab0e4c2cf5c6bab1/build/lib/libc.pcm' not found: module file not found
  #include <new>
   ^
  input_line_1:1:2: note: imported by module 'std' in '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc11/lcg/root/6.29.01-21b454f32e2b6b83ab0e4c2cf5c6bab1/lib/std.pcm'
  Warning in cling::IncrementalParser::CheckABICompatibility():
    Failed to extract C++ standard library version.
  Replaced symbol at_quick_exit cannot be found in JIT!
  Failed to load module std
  <<< cling interactive line includer >>>: fatal error: module file '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc11/lcg/root/6.29.01-21b454f32e2b6b83ab0e4c2cf5c6bab1/build/lib/libc.pcm' not found: module file not found
  <<< cling interactive line includer >>>: note: imported by module '_Builtin_intrinsics' in '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc11/lcg/root/6.29.01-21b454f32e2b6b83ab0e4c2cf5c6bab1/lib/_Builtin_intrinsics.pcm'
  Failed to load module _Builtin_intrinsics
  Failed to load module _Builtin_intrinsics
  Failed to load module std
  python3: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc11/lcg/root/6.29.01-21b454f32e2b6b83ab0e4c2cf5c6bab1/root-6.29.01/core/metacling/src/TCling.cxx:1292: void RegisterCxxModules(cling::Interpreter&): Assertion `clingInterp.getMacro("gROOT") && "Couldn't load gROOT macro?"' failed.
  error: subprocess-exited-with-error
  
  Ã— Preparing metadata (pyproject.toml) did not run successfully.
  â”‚ exit code: -6
  â•°â”€> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc11/external/python3/3.9.14-f1bd82445f2982609f838e795adb062f/bin/python3 /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc11/external/py3-pip/23.1.1-6ca7254dbe849f7b2c3aa4328a6e6ff7/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc11/external/py3-hepdata-lib/0.12.0-129d5c7ef90edc5e88634b8e829c0e16/cmsdist-tmp/tmpynara45i
  cwd: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc11/external/py3-hepdata-lib/0.12.0-129d5c7ef90edc5e88634b8e829c0e16/cmsdist-tmp/pip-req-build-axb0itd8
  Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed
```

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc11

**Comment by vgvassilev** [comment]
@hahnjo, do you have any clue here?

**Comment by hahnjo** [comment]
> @hahnjo, do you have any clue here?

It turns out there was a patch missing / I was a bit over-enthusiastic to drop it as it was only partly replaced with an upstream solution. As a result, runtime modules were not installable / relocatable and `libc.pcm` wasn't found (with assertions enabled it bails out earlier than that, for the same reason).

I added back the patch with the latest push and fixed a couple other issues. @smuzaffar could you add back `hepdata` and restart testing, first on `amd64`? Sorry for testing the installation step of ROOT before!

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
`/usr/bin/python is needed by lcg+root+6.29.01-531a196ab64c8387daaee7e68f7826d6-1-1.x86_64` is due to recently added https://github.com/root-project/root/blob/master/etc/pdg_table_update.py#L1 . I have [suggested](https://github.com/root-project/root/pull/13354#issuecomment-1668496131) to replace it with `/usr/bin/env python`

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

let re-run tests with https://github.com/cms-sw/cmsdist/pull/8640/files which should avoid the `/usr/bin/python is needed by lcg+root+6.29.01` error

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
@hahnjo , any idea why, while generating the root dict, we get error [a] now. Yes `ErrorMatrix` is private typedef here https://github.com/cms-sw/cmssw/blob/master/CondFormats/Alignment/interface/SurveyError.h#L24 
but previously root did not complain about this

[a]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ad3257/34203/build-logs/CondFormats/Alignment/log.html
```
  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_13_3_ROOT6_X_2023-08-08-2300/src/CondFormats/Alignment/interface/SurveyError.h:63:14: error: 'ErrorMatrix' is a private member of 'SurveyError'
 SurveyError::ErrorMatrix SurveyError::matrix() const { return ErrorMatrix(m_errors, m_errors + size_); }
             ^
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_13_3_ROOT6_X_2023-08-08-2300/src/CondFormats/Alignment/interface/SurveyError.h:24:30: note: implicitly declared private here
  typedef align::ErrorMatrix ErrorMatrix;
```

**Comment by vgvassilev** [comment]
> @hahnjo , any idea why, while generating the root dict, we get error [a] now. Yes `ErrorMatrix` is private typedef here https://github.com/cms-sw/cmssw/blob/master/CondFormats/Alignment/interface/SurveyError.h#L24 but previously root did not complain about this
> 
> [a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ad3257/34203/build-logs/CondFormats/Alignment/log.html
> 
> ```
>   /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_13_3_ROOT6_X_2023-08-08-2300/src/CondFormats/Alignment/interface/SurveyError.h:63:14: error: 'ErrorMatrix' is a private member of 'SurveyError'
>  SurveyError::ErrorMatrix SurveyError::matrix() const { return ErrorMatrix(m_errors, m_errors + size_); }
>              ^
> /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_13_3_ROOT6_X_2023-08-08-2300/src/CondFormats/Alignment/interface/SurveyError.h:24:30: note: implicitly declared private here
>   typedef align::ErrorMatrix ErrorMatrix;
> ```

@hahjo, we had either a patch or some logic that does not diagnose accesses to private data members. Maybe we lost that during the upgrade?

**Comment by hahnjo** [comment]
> @hahnjo , any idea why, while generating the root dict, we get error [a] now. Yes `ErrorMatrix` is private typedef here https://github.com/cms-sw/cmssw/blob/master/CondFormats/Alignment/interface/SurveyError.h#L24 but previously root did not complain about this

From a quick analysis, this error is thrown while disambiguating expressions and declarations. A minimal reproducer is
```c++
class A { using T = int; T f(); };
A::T A::f() { return 0; }
```
that fails both in `root` (with LLVM 16)  and (upstream) `clang-repl`.

In this case, Clang's tentative parser looks at `A::T` and complains that it is private before realizing that it is fine as a return type for `A::f()`. Long story short, this must be fixed upstream - thanks for testing and catching this problem! I will come back to you once I update the PR.

**Comment by hahnjo** [comment]
The issue is a bit tricky, a proper solution will require some more work. For now I've added a "slight hack" that addresses the problem at the wrong place, but should be sufficient for us. @smuzaffar could you retrigger testing to see where we get with this?

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by hahnjo** [comment]
@smuzaffar could you maybe retrigger testing? After https://github.com/cms-sw/cmssw/pull/42628, it seems the ROOT6 IBs are now reasonably clean, and we seem to closing in on the final set of changes to make all platforms happy (including Windows).

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by hahnjo** [comment]
Ok, thanks @smuzaffar - it seems CMSSW would be happy with the upgrade :smiley: (just for information, the current plan is to *not* merge it for 6.30 and release that with LLVM 13; LLVM 16 will go in after the branching)

**Pull request closed without merging**
