### PR TITLE
Install glew

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@mrodozov , is not it same as https://github.com/root-project/root/pull/5583 ?

**Comment by mrodozov** [comment]
It's the same I wanted to see if it builds with this

**Comment by oshadura** [comment]
@smuzaffar  @mrodozov  fix is in the ROOT master, sorry for delay and thanks for reporting!

**Comment by smuzaffar** [comment]
thanks @oshadura 
@mrodozov , please update https://github.com/cms-sw/cmsdist/pull/5813 to get latest root commit.

**Pull request closed without merging**
