### PR TITLE
C++ modules ROOT branch rebase

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test for CMSSW_11_0_CXXMODULE_X
although I don't see the point of doing this the IB is wrecked and I never went into details what Shahzad was doing to fix it
https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc700/www/thu/11.0.CXXMODULE-thu-23/CMSSW_11_0_CXXMODULE_X_2019-07-11-2300

**Comment by oshadura** [comment]
@mrodozov thank you anyway! @vgvassilev asked me to update even if IBs are broken. I went through cmsdist IB/CMSSW_11_0_X/cxxmodule and I think I understand how Shahzad setuped modularization process for CMSSW. I will try to fix it if I will manage.

**Comment by mrodozov** [comment]
Alright, btw this config failure happen because of some changes you've put lately on master in the cmake configuration
so now you (or maybe I'll do it) also have to mod the root.spec , see  
`https://github.com/cms-sw/cmsdist/compare/IB/CMSSW_11_0_X/cxxmodule...IB/CMSSW_11_0_X/rootmaster#diff-81217efc115a8de6b75eeef2a6324e47R80`
we had to change that recently on our rootmaster branch

**Comment by oshadura** [comment]
@mrodozov thanks I made a PR https://github.com/cms-sw/cmsdist/pull/5094

**Comment by mrodozov** [comment]
please test for CMSSW_11_0_CXXMODULE_X with cms-sw/cmsdist#5094
lets try the other way around

**Comment by davidlange6** [comment]
hi @mrodozov @oshadura - I understand from @oshadura  that these changes to root are needed for cms-sw/cmsdist#5094 to work.afaik, the way to do that is to merge this PR and then update cms-sw/cmsdist#5094 (or its replacement..) to use the new commit hash. 

So I'd propose we either merge this PR as it is, or else  start a new branch in this repository for it (I can't quickly understand the naming convention of the base branch...)

**Comment by mrodozov** [comment]
I'll make a new branch with the new commit name and everything thats what we usually do. I was testing something that is not yet working as I was expecting. 20 mins, I'll make the changes needed

**Comment by davidlange6** [comment]
thanks and no rush - its not that it will work as is...... but can make it easier for @oshadura (and cmsbot) to test everything together

**Pull request merged**
