### PR TITLE
Issue7955 type first spec 2

### PR DESCRIPTION
**Pull request by smuzaffar**
CMSSW tests of https://github.com/root-project/root/pull/16232

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSW_14_1_ROOT6_X/el8_amd64_gcc12

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_ROOT6_X/el8_amd64_gcc12

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_ROOT6_X/el8_amd64_gcc12

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- pull_request = https://github.com/cms-sw/cmsdist/pull/9392

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_ROOT6_X/el8_amd64_gcc12

**Comment by srimanob** [comment]
@fwyzard @makortel 
Could you please help on the possible issue that the fix from ROOT effect CUDA code? Thanks very much.

More build detail: https://github.com/root-project/root/pull/16232#issuecomment-2299822796
Issue we try to fix: https://github.com/root-project/root/issues/7955
Propose of the fix: https://github.com/root-project/root/pull/16232

**Comment by makortel** [comment]
I'm following up in https://github.com/root-project/root/pull/16232

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_ROOT6_X/el8_amd64_gcc12

**Pull request closed without merging**
