### PR TITLE
Cxxmodules fix symlink rdict resolution

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_CXXMODULE_X

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_CXXMODULE_X

**Comment by smuzaffar** [comment]
@vgvassilev , I am testing your changes ( https://github.com/root-project/root/pull/4288 ) in the PR but looks like we still get the same errors. Unit tests and workflows still fail and complain that they can not find rdict.pcm

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_CXXMODULE_X

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_CXXMODULE_X

**Comment by davidlange6** [comment]
these errors are much later in the workflow than the start-up ones from before. I suggest we merge things and make a new modules IB to work from.
@smuzaffar @vgvassilev

**Comment by smuzaffar** [comment]
this has been included via root updates for CXXMODULE IB ( cmscxx/master/92926c9 )

**Pull request closed without merging**
