### PR TITLE
Fixes needed to compile under clang

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I wasn't able to test that this compiled since the cms build machine lacked X11 and therefore ROOT would not configure.

**Comment by davidlt** [comment]
It will work. It's a double fix. As it forces `thread_local` to be used  in C++11 mode (solves the issue) and then assignment form also solves the same issue. Yet there is a bug, which I noticed while debugging ROOT/TLS. GCC also does not use `thread_local` in C++11 mode, but `static __thread`. `__GNUC_MINOR__ < 80` ==> `__GNUC_MINOR__ < 8`. I will sent a patch on for ROOT on Monday.

I still think that `thread_local` support detection is very fragile in ROOT. More would be needed to detect correct compiler and standard library setup.

**Comment by ktf** [comment]
@degano can you please look into this? Thanks.

**Comment by degano** [comment]
Tested compilation, merging now.

**Pull request merged**
